name: Unit-Test

on:
  pull_request:
    branches:
      - heroku_master

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python Library
        run: |
          sudo pip install -r requirements.txt
      - name: Test
        run: |
          sudo python3 test.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URI: ${{ secrets.DB_URI }}
